default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hcpj_development

test:
  <<: *default
  database: hcpj_test

production:
  <<: *default
  database: hcpj
